const express=require("express");
const router=express.Router();
const {addWinchOrder,addTireOrder,getUserMakeOrderandRating,getOrdersbyServiceType,changeStatusForOrder,ordersAndProfit,reportForProvider}=require("../controllers/serviceProviderOrders");
const upload= require("../configration/uploadFile");
router.post("/winch",upload.single("image"),addWinchOrder);
router.post("/others",upload.single("image"),addTireOrder);
router.get("/userandRating/:id",getUserMakeOrderandRating);
router.get("/",getOrdersbyServiceType);
router.get("/ordersAndProfit",ordersAndProfit);
router.get("/report",reportForProvider);
router.post("/changeStatus",changeStatusForOrder);
module.exports=router;